### PR TITLE
Dbupdate

### PR DESCRIPTION
**Pull request by Brick7Face**
Updates population script with bipolar medications, steps, and adds admin functionality to link to editing items on admin site

### CODE REVIEW

**Comment by MadisonFichtner** [comment]
The checks failed but you're probably good to merge @Brick7Face

**Review by MadisonFichtner — APPROVED** [review]

**Comment by erynplant** [comment]
No, we need to make sure the tests are passing - that's the point of the tests. It looks like something is wrong with the migrations, why are there migrations at all for this PR? It doesn't look like there are any real changes to models.py

**Comment by erynplant** [comment]
Also, can we just remove the .eggs/ folder from github and add it to the .gitignore? Or does it need to be checked in?

**Comment by Brick7Face** [comment]
The migrations are just for the local db, and the site wouldn't run right otherwise. The .eggs folder needs to be there for the sonarcloud stuff but i think they're generated so we might be able to add them to the .gitignore. I'll do that quick

**Comment by erynplant** [comment]
Hmm ok, do you know what's causing the tests to fail?

**Comment by Brick7Face** [comment]
I don't, I'm looking into that now. It seems like it's kinda random cause it'll fail and then pass

**Comment by Brick7Face** [comment]
Nvm looks like it was the migrations, I just needed to pull and merge again. Should be good now for those things.

**Pull request merged**
